language: node_js

node_js:
  - "8.11.1"

sudo: required

notifications:
  email: false

services:
  - docker

before_install:
  - docker run -it -d -p 3001:3001 hunterlong/btcregtest-insight:latest

script:
  - sleep 30
  - npm test